[log]
  level = "ERROR"
  filePath = "./traefik.log"

[entryPoints.web]
  address = ":80"
  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

[entryPoints.websecure]
  address = ":443"
  [entryPoints.websecure.http.tls]
    certResolver = "myresolver"

[certificatesResolvers.myresolver.acme]
  email = "your-email@example.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]


[api]
  dashboard = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
network = "traefikNetwork"
exposedByDefault = false
